version: "3.8"
services:
  wireguard:
    image: wireguard_gaming:v0.1.0
    cap_add:
      - NET_ADMIN 
    volumes:
      - ./config:/etc/wireguard
    environment:
      INTERFACE_CONFIG_PATH: /etc/config/wg0.conf
      SUBNET: 10.42.42.0/24
  wireguard-ui:
    image: ngoduykhanh/wireguard-ui:0.6.2
    volumes:
      - ./config/etc/wireguard
    environment:
      SESSION_SECRET: <random data>
      WGUI_SERVER_INTERFACE_ADDRESSES: 10.42.42.1/24
      WGUI_SERVER_LISTEN_PORT: 42443
      WGUI_DEFAULT_CLIENT_USE_SERVER_DNS: false

